### ISSUE TITLE
Evaluation Metrics Show Zero Values Despite Correct Label Loading in Training

### ISSUE THREAD

**Issue by xoxososw** [alibaba/esod#3]
Hello, may I ask why when I am training, it keeps showing：
 Epoch   gpu_mem       box       obj       cls      pixl      area      dist     total    labels  img_size
      0/49    0.912G    0.1011    0.1259    0.0476  0.005673         0         0    0.2758       171      1024: 100%|██| 809/809 [02:12<00:00,  6.12it/s]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95        BPR     Occupy: 100%|██████| 69/69 [00:02<00:00, 24.53it/s]
                 all        548          0          0          0          0          0        nan          1
I've checked that my val labels are reading correctly, but why does the assessment keep showing 0 for labels and 0 for other metrics?

**Comment by JYJAI** [comment]
I encountered the same problem.

**Comment by ryzdacccount** [comment]
我也遇到了相同的问题

**Comment by WHY-student** [comment]
I'm following, do you valiate the results of training?

**Comment by WHY-student** [comment]
I solve the problem in visDrone, the error in data_prepare.py cause this.

the path of annotations of mask isn't correctly defined. The modified function as following:

```python

def prepare_visdrone():
    
    name_dict = {'0': 'ignored regions', '1': 'pedestrian', '2': 'people',
                 '3': 'bicycle', '4': 'car', '5': 'van', '6': 'truck',
                 '7': 'tricycle', '8': 'awning-tricycle', '9': 'bus',
                 '10': 'motor', '11': 'others'}
    split_dict = {'test-dev': 'test-dev.txt', 'val': 'val.txt', 'train': 'train.txt'}
    root = opt.dataset

    os.makedirs(join(root, 'split'), exist_ok=True)
    for sub_dir in glob(join(root, 'VisDrone2019-DET-*')):
        os.makedirs(join(sub_dir, 'labels'), exist_ok=True)
        images = sorted(glob(join(sub_dir, 'images', '*.jpg')))
        if 'test-challenge' in sub_dir:
            with open(join(root, 'split', 'test-challenge.txt'), 'w+') as f:
                f.writelines([line + '\n' for line in images])
            continue

        data_paths = []
        for image_path in tqdm(images):
            image = cv2.imread(image_path)
            height, width, _ = image.shape
            label_path = image_path.replace('images', 'annotations').replace('.jpg', '.txt')
            if "masked" in label_path:
                continue
            assert exists(label_path)
            label_lines = []
            masked = False
            # <bbox_left>,<bbox_top>,<bbox_width>,<bbox_height>,<score>,<object_category>,<truncation>,<occlusion>
            for line in _readlines(label_path):
                if line[-1] == ',':
                    line = line[:-1]
                x1, y1, w, h, score, cls, truncation, occlusion = list(map(int, line.split(',')))
                if cls in [0, 11]:
                    image[y1:y1 + h, x1:x1 + w, :] = 85
                    masked = True
                elif truncation < 2 and (occlusion < 2 or True):
                    xc, yc = x1 + w / 2., y1 + h / 2.
                    label_lines.append(('%d' + ' %.6f' * 4 + '\n') %
                                       (cls - 1, xc / width, yc / height, w / width, h / height))
                else:
                    pass
            if masked:
                image_path = image_path.replace('.jpg', '_masked.jpg')
                cv2.imwrite(image_path, image)
            # for consistency
            # with open(image_path.replace('.jpg', '.txt'), 'w+') as f:
            #     f.writelines(label_lines)
            label_path = image_path.replace('images', 'labels').replace('.jpg', '.txt')
            with open(label_path, 'w+') as f:
                f.writelines(label_lines)

            gen_mask(label_path, image, cls_ratio=True)

            data_paths.append(image_path + '\n')
        
        with open(join(root, 'split', split_dict[basename(sub_dir)[17:]]), 'w+') as f:
            f.writelines(data_paths)

```

It's important that **label_path = image_path.replace('images', 'labels').replace('.jpg', '.txt')**

**Comment by xoxososw** [comment]
> I solve the problem in visDrone, the error in data_prepare.py cause this.
> 
> the path of annotations of mask isn't correctly defined. The modified function as following:
> 
> ```python
> def prepare_visdrone():
>     
>     name_dict = {'0': 'ignored regions', '1': 'pedestrian', '2': 'people',
>                  '3': 'bicycle', '4': 'car', '5': 'van', '6': 'truck',
>                  '7': 'tricycle', '8': 'awning-tricycle', '9': 'bus',
>                  '10': 'motor', '11': 'others'}
>     split_dict = {'test-dev': 'test-dev.txt', 'val': 'val.txt', 'train': 'train.txt'}
>     root = opt.dataset
> 
>     os.makedirs(join(root, 'split'), exist_ok=True)
>     for sub_dir in glob(join(root, 'VisDrone2019-DET-*')):
>         os.makedirs(join(sub_dir, 'labels'), exist_ok=True)
>         images = sorted(glob(join(sub_dir, 'images', '*.jpg')))
>         if 'test-challenge' in sub_dir:
>             with open(join(root, 'split', 'test-challenge.txt'), 'w+') as f:
>                 f.writelines([line + '\n' for line in images])
>             continue
> 
>         data_paths = []
>         for image_path in tqdm(images):
>             image = cv2.imread(image_path)
>             height, width, _ = image.shape
>             label_path = image_path.replace('images', 'annotations').replace('.jpg', '.txt')
>             if "masked" in label_path:
>                 continue
>             assert exists(label_path)
>             label_lines = []
>             masked = False
>             # <bbox_left>,<bbox_top>,<bbox_width>,<bbox_height>,<score>,<object_category>,<truncation>,<occlusion>
>             for line in _readlines(label_path):
>                 if line[-1] == ',':
>                     line = line[:-1]
>                 x1, y1, w, h, score, cls, truncation, occlusion = list(map(int, line.split(',')))
>                 if cls in [0, 11]:
>                     image[y1:y1 + h, x1:x1 + w, :] = 85
>                     masked = True
>                 elif truncation < 2 and (occlusion < 2 or True):
>                     xc, yc = x1 + w / 2., y1 + h / 2.
>                     label_lines.append(('%d' + ' %.6f' * 4 + '\n') %
>                                        (cls - 1, xc / width, yc / height, w / width, h / height))
>                 else:
>                     pass
>             if masked:
>                 image_path = image_path.replace('.jpg', '_masked.jpg')
>                 cv2.imwrite(image_path, image)
>             # for consistency
>             # with open(image_path.replace('.jpg', '.txt'), 'w+') as f:
>             #     f.writelines(label_lines)
>             label_path = image_path.replace('images', 'labels').replace('.jpg', '.txt')
>             with open(label_path, 'w+') as f:
>                 f.writelines(label_lines)
> 
>             gen_mask(label_path, image, cls_ratio=True)
> 
>             data_paths.append(image_path + '\n')
>         
>         with open(join(root, 'split', split_dict[basename(sub_dir)[17:]]), 'w+') as f:
>             f.writelines(data_paths)
> ```
> 
> It's important that **label_path = image_path.replace('images', 'labels').replace('.jpg', '.txt')**

Hi, I read your solution, can I ask you if your labeling file (i.e. the labels folder and not the annotations folder), is it in the original visdrone format or the coco format, is it something like the following？:
170,113,15,13,1,4,0,0
102,81,13,13,1,4,0,0
415,207,5,9,1,1,0,0
428,197,8,13,1,1,0,1
232,385,13,31,0,0,11,0,0

**Comment by WHY-student** [comment]
> Hi, I read your solution, can I ask you if your labeling file (i.e. the labels folder and not the annotations folder), is it in the original visdrone format or the coco format, is it something like the following？: 170,113,15,13,1,4,0,0 102,81,13,13,1,4,0,0 415,207,5,9,1,1,0,0 428,197,8,13,1,1,0,1 232,385,13,31,0,0,11,0,0


exactly, I got the files as:
3 0.467708 0.572222 0.028125 0.085185
3 0.509896 0.590741 0.032292 0.085185
3 0.472656 0.703704 0.034896 0.101852
9 0.512760 0.757407 0.014063 0.050000
1 0.513281 0.752778 0.009896 0.035185
9 0.228125 0.874074 0.025000 0.042593
0 0.239844 0.987963 0.014063 0.024074


the content your shown is same as the annotations folder:
871,572,54,92,1,4,0,0
948,592,62,92,1,4,0,0
874,705,67,110,1,4,0,1
971,791,27,54,1,10,0,1
976,794,19,38,1,2,0,1
414,921,48,46,1,10,0,1
447,1054,27,26,1,1,1,0
430,902,27,49,1,1,0,1
405,837,55,52,1,8,0,1
416,856,19,36,1,2,0,1
349,796,60,61,1,8,0,1
378,753,39,44,1,10,0,1


you can view them in ./visDrone/VisDrone2019-DET-val/labels/0000001_02999_d_0000005_masked.txt   ./visDrone/VisDrone2019-DET-val/annotations/0000001_02999_d_0000005.txt

**Comment by WHY-student** [comment]
> > > Hi, I read your solution, can I ask you if your labeling file (i.e. the labels folder and not the annotations folder), is it in the original visdrone format or the coco format, is it something like the following？: 170,113,15,13,1,4,0,0 102,81,13,13,1,4,0,0 415,207,5,9,1,1,0,0 428,197,8,13,1,1,0,1 232,385,13,31,0,0,11,0,0
> > 
> > 
> > if successfully run, the code
> > ```
> > label_lines.append(('%d' + ' %.6f' * 4 + '\n') %
> >                                        (cls - 1, xc / width, yc / height, w / width, h / height))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > will be used to get coco_format.
> > if you got the same label as original, maybe you should check this part.
> > Lastly, I got the files as: 3 0.467708 0.572222 0.028125 0.085185 3 0.509896 0.590741 0.032292 0.085185 3 0.472656 0.703704 0.034896 0.101852 9 0.512760 0.757407 0.014063 0.050000 1 0.513281 0.752778 0.009896 0.035185 9 0.228125 0.874074 0.025000 0.042593 0 0.239844 0.987963 0.014063 0.024074
> > the content your shown is same as the annotations folder: 871,572,54,92,1,4,0,0 948,592,62,92,1,4,0,0 874,705,67,110,1,4,0,1 971,791,27,54,1,10,0,1 976,794,19,38,1,2,0,1 414,921,48,46,1,10,0,1 447,1054,27,26,1,1,1,0 430,902,27,49,1,1,0,1 405,837,55,52,1,8,0,1 416,856,19,36,1,2,0,1 349,796,60,61,1,8,0,1 378,753,39,44,1,10,0,1
> > you can view them in ./visDrone/VisDrone2019-DET-val/labels/0000001_02999_d_0000005_masked.txt ./visDrone/VisDrone2019-DET-val/annotations/0000001_02999_d_0000005.txt
> 
> Thanks for the answer, so the data in your ./visDrone/VisDrone2019-DET-val/labels/0000001_02999_d_0000005_masked.txt , is it similar to the following？: 170,113,15,13,1,4,0,0 102,81,13,13,1,4,0,0 415,207,5,9,1,1,0,0 428,197,8,13,1,1,0,1 232,385,13,31,0,0,11,0,0

No, json format is more similar as mine.

**Comment by wangsada** [comment]
> 我在 visDrone 中解决了这个问题，data_prepare.py 中的错误导致了这个问题。
> 
> mask注释的路径定义不正确，修改后的函数如下：
> 
> def prepare_visdrone():
>     
>     name_dict = {'0': 'ignored regions', '1': 'pedestrian', '2': 'people',
>                  '3': 'bicycle', '4': 'car', '5': 'van', '6': 'truck',
>                  '7': 'tricycle', '8': 'awning-tricycle', '9': 'bus',
>                  '10': 'motor', '11': 'others'}
>     split_dict = {'test-dev': 'test-dev.txt', 'val': 'val.txt', 'train': 'train.txt'}
>     root = opt.dataset
> 
>     os.makedirs(join(root, 'split'), exist_ok=True)
>     for sub_dir in glob(join(root, 'VisDrone2019-DET-*')):
>         os.makedirs(join(sub_dir, 'labels'), exist_ok=True)
>         images = sorted(glob(join(sub_dir, 'images', '*.jpg')))
>         if 'test-challenge' in sub_dir:
>             with open(join(root, 'split', 'test-challenge.txt'), 'w+') as f:
>                 f.writelines([line + '\n' for line in images])
>             continue
> 
>         data_paths = []
>         for image_path in tqdm(images):
>             image = cv2.imread(image_path)
>             height, width, _ = image.shape
>             label_path = image_path.replace('images', 'annotations').replace('.jpg', '.txt')
>             if "masked" in label_path:
>                 continue
>             assert exists(label_path)
>             label_lines = []
>             masked = False
>             # <bbox_left>,<bbox_top>,<bbox_width>,<bbox_height>,<score>,<object_category>,<truncation>,<occlusion>
>             for line in _readlines(label_path):
>                 if line[-1] == ',':
>                     line = line[:-1]
>                 x1, y1, w, h, score, cls, truncation, occlusion = list(map(int, line.split(',')))
>                 if cls in [0, 11]:
>                     image[y1:y1 + h, x1:x1 + w, :] = 85
>                     masked = True
>                 elif truncation < 2 and (occlusion < 2 or True):
>                     xc, yc = x1 + w / 2., y1 + h / 2.
>                     label_lines.append(('%d' + ' %.6f' * 4 + '\n') %
>                                        (cls - 1, xc / width, yc / height, w / width, h / height))
>                 else:
>                     pass
>             if masked:
>                 image_path = image_path.replace('.jpg', '_masked.jpg')
>                 cv2.imwrite(image_path, image)
>             # for consistency
>             # with open(image_path.replace('.jpg', '.txt'), 'w+') as f:
>             #     f.writelines(label_lines)
>             label_path = image_path.replace('images', 'labels').replace('.jpg', '.txt')
>             with open(label_path, 'w+') as f:
>                 f.writelines(label_lines)
> 
>             gen_mask(label_path, image, cls_ratio=True)
> 
>             data_paths.append(image_path + '\n')
>         
>         with open(join(root, 'split', split_dict[basename(sub_dir)[17:]]), 'w+') as f:
>             f.writelines(data_paths)
> 重要的是**label_path = image_path.replace('images', 'labels').replace('.jpg', '.txt')**
您好，我按照你修改后的运行，但是问题依旧存在，有没有什么别的解决方法

**Comment by WHY-student** [comment]
你可以debug看看，数据集转换的时候读取的标签文件位置是否存在，如果不存在就会出现label为0这个问题。

**Comment by wangsada** [comment]
具体要怎么实现呢，没太看的明白这个


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/esod"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年3月11日(星期二) 下午5:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/esod] Evaluation Metrics Show Zero Values Despite Correct Label Loading in Training (Issue #3)



   
你可以debug看看，数据集转换的时候读取的标签文件位置是否存在，如果不存在就会出现label为0这个问题。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
  WHY-student left a comment (alibaba/esod#3)
 
你可以debug看看，数据集转换的时候读取的标签文件位置是否存在，如果不存在就会出现label为0这个问题。

**Comment by kail8** [comment]
Thanks for the constructive discussions. I have updated the processing logic in the latest code at `esod/scripts/data_prepare.py`, which should solve the above problems.

**Comment by YXG2021** [comment]
> 你可以debug看看，数据集转换的时候读取的标签文件位置是否存在，如果不存在就会出现label为0这个问题。

可是虽然我的labels在训练过程中不为零，不过area和dist一直是0,每个epochs结束后的验证中，P, R,也都是0,

**Comment by YXG2021** [comment]
> I solve the problem in visDrone, the error in data_prepare.py cause this.
> 
> the path of annotations of mask isn't correctly defined. The modified function as following:
> 
> def prepare_visdrone():
>     
>     name_dict = {'0': 'ignored regions', '1': 'pedestrian', '2': 'people',
>                  '3': 'bicycle', '4': 'car', '5': 'van', '6': 'truck',
>                  '7': 'tricycle', '8': 'awning-tricycle', '9': 'bus',
>                  '10': 'motor', '11': 'others'}
>     split_dict = {'test-dev': 'test-dev.txt', 'val': 'val.txt', 'train': 'train.txt'}
>     root = opt.dataset
> 
>     os.makedirs(join(root, 'split'), exist_ok=True)
>     for sub_dir in glob(join(root, 'VisDrone2019-DET-*')):
>         os.makedirs(join(sub_dir, 'labels'), exist_ok=True)
>         images = sorted(glob(join(sub_dir, 'images', '*.jpg')))
>         if 'test-challenge' in sub_dir:
>             with open(join(root, 'split', 'test-challenge.txt'), 'w+') as f:
>                 f.writelines([line + '\n' for line in images])
>             continue
> 
>         data_paths = []
>         for image_path in tqdm(images):
>             image = cv2.imread(image_path)
>             height, width, _ = image.shape
>             label_path = image_path.replace('images', 'annotations').replace('.jpg', '.txt')
>             if "masked" in label_path:
>                 continue
>             assert exists(label_path)
>             label_lines = []
>             masked = False
>             # <bbox_left>,<bbox_top>,<bbox_width>,<bbox_height>,<score>,<object_category>,<truncation>,<occlusion>
>             for line in _readlines(label_path):
>                 if line[-1] == ',':
>                     line = line[:-1]
>                 x1, y1, w, h, score, cls, truncation, occlusion = list(map(int, line.split(',')))
>                 if cls in [0, 11]:
>                     image[y1:y1 + h, x1:x1 + w, :] = 85
>                     masked = True
>                 elif truncation < 2 and (occlusion < 2 or True):
>                     xc, yc = x1 + w / 2., y1 + h / 2.
>                     label_lines.append(('%d' + ' %.6f' * 4 + '\n') %
>                                        (cls - 1, xc / width, yc / height, w / width, h / height))
>                 else:
>                     pass
>             if masked:
>                 image_path = image_path.replace('.jpg', '_masked.jpg')
>                 cv2.imwrite(image_path, image)
>             # for consistency
>             # with open(image_path.replace('.jpg', '.txt'), 'w+') as f:
>             #     f.writelines(label_lines)
>             label_path = image_path.replace('images', 'labels').replace('.jpg', '.txt')
>             with open(label_path, 'w+') as f:
>                 f.writelines(label_lines)
> 
>             gen_mask(label_path, image, cls_ratio=True)
> 
>             data_paths.append(image_path + '\n')
>         
>         with open(join(root, 'split', split_dict[basename(sub_dir)[17:]]), 'w+') as f:
>             f.writelines(data_paths)
> It's important that **label_path = image_path.replace('images', 'labels').replace('.jpg', '.txt')**
你的VisDrone.yaml文件内容是下面这样吗：
train: ./VisDrone/split/train.txt  # 4K images
val: ./VisDrone/split/val.txt  # 700 imageS
test: ./VisDrone/split/test-dev.txt  # 20288 of 40670 images, submit to https:/competitions.codalab.org/competitions/20794

**Comment by judycpChen** [comment]
> 你可以debug看看，数据集转换的时候读取的标签文件位置是否存在，如果不存在就会出现label为0这个问题。

Hi, did you manage to resurface? How exactly did you solve the problem of PR and other metrics being 0. I did what you said above but it didn't solve it!

**Comment by WHY-student** [comment]
> > I solve the problem in visDrone, the error in data_prepare.py cause this.
> > the path of annotations of mask isn't correctly defined. The modified function as following:
> > def prepare_visdrone():
> > ```
> > name_dict = {'0': 'ignored regions', '1': 'pedestrian', '2': 'people',
> >              '3': 'bicycle', '4': 'car', '5': 'van', '6': 'truck',
> >              '7': 'tricycle', '8': 'awning-tricycle', '9': 'bus',
> >              '10': 'motor', '11': 'others'}
> > split_dict = {'test-dev': 'test-dev.txt', 'val': 'val.txt', 'train': 'train.txt'}
> > root = opt.dataset
> > 
> > os.makedirs(join(root, 'split'), exist_ok=True)
> > for sub_dir in glob(join(root, 'VisDrone2019-DET-*')):
> >     os.makedirs(join(sub_dir, 'labels'), exist_ok=True)
> >     images = sorted(glob(join(sub_dir, 'images', '*.jpg')))
> >     if 'test-challenge' in sub_dir:
> >         with open(join(root, 'split', 'test-challenge.txt'), 'w+') as f:
> >             f.writelines([line + '\n' for line in images])
> >         continue
> > 
> >     data_paths = []
> >     for image_path in tqdm(images):
> >         image = cv2.imread(image_path)
> >         height, width, _ = image.shape
> >         label_path = image_path.replace('images', 'annotations').replace('.jpg', '.txt')
> >         if "masked" in label_path:
> >             continue
> >         assert exists(label_path)
> >         label_lines = []
> >         masked = False
> >         # <bbox_left>,<bbox_top>,<bbox_width>,<bbox_height>,<score>,<object_category>,<truncation>,<occlusion>
> >         for line in _readlines(label_path):
> >             if line[-1] == ',':
> >                 line = line[:-1]
> >             x1, y1, w, h, score, cls, truncation, occlusion = list(map(int, line.split(',')))
> >             if cls in [0, 11]:
> >                 image[y1:y1 + h, x1:x1 + w, :] = 85
> >                 masked = True
> >             elif truncation < 2 and (occlusion < 2 or True):
> >                 xc, yc = x1 + w / 2., y1 + h / 2.
> >                 label_lines.append(('%d' + ' %.6f' * 4 + '\n') %
> >                                    (cls - 1, xc / width, yc / height, w / width, h / height))
> >             else:
> >                 pass
> >         if masked:
> >             image_path = image_path.replace('.jpg', '_masked.jpg')
> >             cv2.imwrite(image_path, image)
> >         # for consistency
> >         # with open(image_path.replace('.jpg', '.txt'), 'w+') as f:
> >         #     f.writelines(label_lines)
> >         label_path = image_path.replace('images', 'labels').replace('.jpg', '.txt')
> >         with open(label_path, 'w+') as f:
> >             f.writelines(label_lines)
> > 
> >         gen_mask(label_path, image, cls_ratio=True)
> > 
> >         data_paths.append(image_path + '\n')
> >     
> >     with open(join(root, 'split', split_dict[basename(sub_dir)[17:]]), 'w+') as f:
> >         f.writelines(data_paths)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It's important that **label_path = image_path.replace('images', 'labels').replace('.jpg', '.txt')**
> > 你的VisDrone.yaml文件内容是下面这样吗：
> > train: ./VisDrone/split/train.txt  # 4K images
> > val: ./VisDrone/split/val.txt  # 700 imageS
> > test: ./VisDrone/split/test-dev.txt  # 20288 of 40670 images, submit to https:/competitions.codalab.org/competitions/20794

my code is following:
train: /new_data/why/datasets/visDrone/split/train.txt  # 4K images
val: /new_data/why/datasets/visDrone/split/val.txt  # 700 imageS
test: /new_data/why/datasets/visDrone/split/test-dev.txt  # 20288 of 40670 images, submit to https:/competitions.codalab.org/competitions/20794

maybe you should use absolute path

**Comment by WHY-student** [comment]
> > 你可以debug看看，数据集转换的时候读取的标签文件位置是否存在，如果不存在就会出现label为0这个问题。
> 
> Hi, did you manage to resurface? How exactly did you solve the problem of PR and other metrics being 0. I did what you said above but it didn't solve it!

maybe you should print the label_path and image_path in following code:
          label_path = image_path.replace('images', 'labels').replace('.jpg', '.txt')
and make sure the path is exist and the label file is not empty.

**Comment by WHY-student** [comment]
> > 你可以debug看看，数据集转换的时候读取的标签文件位置是否存在，如果不存在就会出现label为0这个问题。
> 
> 可是虽然我的labels在训练过程中不为零，不过area和dist一直是0,每个epochs结束后的验证中，P, R,也都是0,

这个问题就是最初的问题，你可能要检查一下你的标注文件是否是空的

**Comment by judycpChen** [comment]
> 也许您应该在下面的代码中打印 label_path 和 image_path：
> label_path = image_path.replace('图像', '标签').replace('.jpg', '.txt')
> 并确保路径存在且标签文件不为空。

我检查了我的所有标签文件不为空，并且将visdrone.yaml文件里的路径改为了绝对路径，但是训练时area和dist都为空，验证时的指标依然为空，我检查到在计算loss时，跳过了计算area和dist，请问你是否修改了这部分代码以成功训练和验证？

![Image](https://github.com/user-attachments/assets/79449886-d396-40f8-b71e-f77a4b65b14b)

**Comment by benderick** [comment]
你的验证集下需要有相应的masks（通过data-prepare.py生成）.

<img width="324" height="275" alt="Image" src="https://github.com/user-attachments/assets/925e8f79-9937-4c00-a1c7-642ba4b28277" />
